security:
  encoders:
    App\Entity\User:
      algorithm: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN

  providers:
    in_memory: { memory: ~ }
    app_provider:
      entity:
        class: App\Entity\User
        property: username


  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api_login:
      pattern:  ^/api/login/
      stateless: true
      anonymous: true

    api:
      pattern: ^/api/
      anonymous: true
      stateless: true
      guard:
        authenticators:
        - lexik_jwt_authentication.jwt_token_authenticator
        provider: app_provider
      logout:
        path: /api/logout
        target: /api/login

    main:
      anonymous: true

  access_control:
  - { path: ^/api/login,    roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/api/doc,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/api,          roles: IS_AUTHENTICATED_FULLY }
